// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "<挂起>", Scope = "member", Target = "~M:SIE.Web.Dock.Gantt.Areas.SchedulGantt.Controllers.LoadGanttController.LoadData(System.Nullable{System.Double},System.Nullable{System.Double},System.Nullable{SIE.Domain.State},System.DateTime,System.DateTime)~SIE.Web.Json.EntityJson")]
[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "<挂起>", Scope = "member", Target = "~M:SIE.Web.Dock.Gantt.Areas.Dock.Controllers.LoadGanttController.LoadData(System.Nullable{System.Double},System.Nullable{System.Double},System.Nullable{SIE.Domain.State},System.DateTime,System.DateTime)~SIE.Web.Dock.Gantt.Areas.PlatformGantt.ViewModel.LoadData")]
[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "<挂起>", Scope = "member", Target = "~M:SIE.Web.Dock.Gantt.Areas.PlatformGantt.Controllers.LoadGanttController.LoadData(System.Nullable{System.Double},System.Nullable{System.Double},System.Nullable{System.Int32},System.DateTime,System.DateTime)~SIE.Web.Dock.Gantt.Areas.Dock.ViewModel.LoadData")]
[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "<挂起>", Scope = "member", Target = "~M:SIE.Web.Dock.Gantt.Areas.Dock.Controllers.LoadGanttController.LoadData(System.Nullable{System.Double},System.Nullable{System.Double},System.Nullable{System.Int32},System.DateTime,System.DateTime)~SIE.Web.Dock.Gantt.Areas.Dock.ViewModel.LoadData")]
[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "<挂起>", Scope = "member", Target = "~M:SIE.Web.Dock.Gantt.Areas.Dock.Controllers.SaveGanttController.SaveOrderGanttData(System.String)~System.String")]
[assembly: SuppressMessage("Critical Code Smell", "S3776:Cognitive Complexity of methods should not be too high", Justification = "<挂起>", Scope = "member", Target = "~M:SIE.Web.Dock.Gantt.Areas.Dock.Controllers.SaveGanttController.HandleAddData(System.Collections.Generic.List{SIE.Web.Dock.Gantt.Areas.Dock.ViewModel.SaveAppointModel},System.Collections.Generic.List{SIE.Dock.DockAppoints.DockAppoint},SIE.Domain.EntityList{SIE.Dock.DockMaintains.DockMaintain},SIE.Domain.EntityList{SIE.Dock.YardZones.DockHandling})~SIE.Web.Dock.Gantt.Areas.Dock.ViewModel.SaveReturnMsg")]
[assembly: SuppressMessage("Minor Code Smell", "S1192:String literals should not be duplicated", Justification = "<挂起>", Scope = "member", Target = "~M:SIE.Web.Dock.Gantt.Areas.Dock.Controllers.LoadGanttController.LoadData(System.Nullable{System.Double},System.Nullable{System.Double},System.Nullable{System.Int32},System.DateTime,System.DateTime,System.String,System.String)~SIE.Web.Dock.Gantt.Areas.Dock.ViewModel.LoadData")]
