<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CodeAnalysisRuleSet>..\..\..\..\.sonarlint\sie.smomcsharp.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\..\..\platform\smom\</OutputPath>
    <DocumentationFile>..\..\..\..\platform\smom\net6.0\SIE.Web.MES.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\..\platform\smom\</OutputPath>
    <DocumentationFile>..\..\..\..\platform\smom\net6.0\SIE.Web.MES.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Andon\Commands\AndonUpholdSaveCommands.js" />
    <None Remove="Andon\Commands\ThresholdDLTemplateCommand.js" />
    <None Remove="Andon\Commands\ThresholdImportCommand.js" />
    <None Remove="BarcodeProcesses\Commands\AfterAddProcessDetailCommand.js" />
    <None Remove="BarcodeProcesses\Commands\SynWoProcessListCommand.js" />
    <None Remove="BarcodeProcesses\Commands\WoProcessDetailSaveCommand.js" />
    <None Remove="BarcodeProcesses\Scripts\EmployeeMultiComboPopup.js" />
    <None Remove="BatchGeneration\Commands\BatchWoGenerateCommand.js" />
    <None Remove="BatchGeneration\Commands\GenerateAndPrintCommand.js" />
    <None Remove="BatchGeneration\Commands\GenerateCommand.js" />
    <None Remove="BatchProductRoutings\Commands\BatchProductCriteriaCommand.js" />
    <None Remove="BatchProductRoutings\Commands\PauseCommand.js" />
    <None Remove="BatchProductRoutings\Controls\BatchRoutingDesignControl.js" />
    <None Remove="BatchProductRoutings\Scripts\BatchRoutingLayout.js" />
    <None Remove="BatchWIP\Commands\ExportReportCommand.js" />
    <None Remove="BatchWIP\Scripts\BatchWipProductProcessBehavior.js" />
    <None Remove="BatchWIP\Scripts\BatchWipProductProcessDtlBehavior.js" />
    <None Remove="BatchWIP\Scripts\BatchWipRecordBehavior.js" />
    <None Remove="BlueLable\Commands\BlueLableLevelDLTemplateCommand.js" />
    <None Remove="BlueLable\Commands\BlueLableLevelImportCommand.js" />
    <None Remove="Checker\Commands\CheckerUpholdSaveCommands.js" />
    <None Remove="Common\Commands\ImportDataCommonCommand.js" />
    <None Remove="Common\CommonFuns.js" />
    <None Remove="DataBarcode\Commands\DataBarcodeDeleteCommand.js" />
    <None Remove="DataBarcode\Commands\DataBarcodeImportCommand.js" />
    <None Remove="DataBarcode\Commands\DataBarcodeLabelPrintCommand.js" />
    <None Remove="Edge\Commands\ReSubmitMessageCommand.js" />
    <None Remove="Fixture\Commands\FixtureUpholdSaveCommands.js" />
    <None Remove="InspectionStandards\Commands\ImportInspectionCommand.js" />
    <None Remove="InspectionStandards\Commands\InspectionAddCommand.js" />
    <None Remove="InspectionStandards\Commands\InspectionSaveCommand.js" />
    <None Remove="ItemChecker\Commands\CheckerItemDeleteCommand.js" />
    <None Remove="ItemChecker\Commands\CheckerItemDisableCommand.js" />
    <None Remove="ItemChecker\Commands\CheckerItemDLTemplateCommand.js" />
    <None Remove="ItemChecker\Commands\CheckerItemEditCommand.js" />
    <None Remove="ItemChecker\Commands\CheckerItemEnableCommand.js" />
    <None Remove="ItemChecker\Commands\CheckerItemImportCommand.js" />
    <None Remove="ItemChecker\Commands\CheckerItemSaveCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemDeleteCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemDisableCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemDLTemplateCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemEditCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemEnableCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemImportCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemImportEquipCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemImportItemCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemImportProcessCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemImportUniqueCodeCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemLabelPrintCommand.js" />
    <None Remove="ItemEquipAccount\Commands\EquipAccountItemSaveCommand.js" />
    <None Remove="ItemFixture\Commands\FixtureItemDeleteCommand.js" />
    <None Remove="ItemFixture\Commands\FixtureItemDisableCommand.js" />
    <None Remove="ItemFixture\Commands\FixtureItemDLTemplateCommand.js" />
    <None Remove="ItemFixture\Commands\FixtureItemEditCommand.js" />
    <None Remove="ItemFixture\Commands\FixtureItemEnableCommand.js" />
    <None Remove="ItemFixture\Commands\FixtureItemImportCommand.js" />
    <None Remove="ItemFixture\Commands\FixtureItemSaveCommand.js" />
    <None Remove="ItemLine\Commands\ProductLineDeleteCommand.js" />
    <None Remove="ItemLine\Commands\ProductLineDisableCommand.js" />
    <None Remove="ItemLine\Commands\ProductLineDLTemplateCommand.js" />
    <None Remove="ItemLine\Commands\ProductLineEditCommands.js" />
    <None Remove="ItemLine\Commands\ProductLineEnableCommand.js" />
    <None Remove="ItemLine\Commands\ProductLineImportCommand.js" />
    <None Remove="ItemLine\Commands\ProductLineImportItemCommand.js" />
    <None Remove="ItemLine\Commands\ProductLineImportProcessCommand.js" />
    <None Remove="ItemLine\Commands\ProductLineImportWipResourceCommand.js" />
    <None Remove="ItemLine\Commands\ProductLineSaveCommands.js" />
    <None Remove="ItemProcess\Commands\ProcessItemDeleteCommand.js" />
    <None Remove="ItemProcess\Commands\ProcessItemDisableCommand.js" />
    <None Remove="ItemProcess\Commands\ProcessItemDLTemplateCommand.js" />
    <None Remove="ItemProcess\Commands\ProcessItemEditCommand.js" />
    <None Remove="ItemProcess\Commands\ProcessItemEnableCommand.js" />
    <None Remove="ItemProcess\Commands\ProcessItemImportCommand.js" />
    <None Remove="ItemProcess\Commands\ProcessItemSaveCommand.js" />
    <None Remove="LineAndon\Commands\AdonlineLabelPrintCommand.js" />
    <None Remove="LineAndon\Commands\AndonLineDLTemplateCommand.js" />
    <None Remove="LineAndon\Commands\AndonLineImportCommand.js" />
    <None Remove="LineAndon\Commands\AndonLineLabelPrintCommand.js" />
    <None Remove="LoadItems\DeductItems\Commands\WoCostItemAddCommand.js" />
    <None Remove="LoadItems\DeductItems\Commands\WoCostItemCloseCommand.js" />
    <None Remove="LoadItems\DeductItems\Commands\WoCostItemDeleteCommand.js" />
    <None Remove="LoadItems\DeductItems\Commands\WoCostItemEditCommand.js" />
    <None Remove="LoadItems\DeductItems\Commands\WoCostItemSaveCommand.js" />
    <None Remove="LoadItems\DeductItems\Commands\WoCostItemSubmitCommand.js" />
    <None Remove="LoadItems\DeductItems\Commands\WoCostItemSupplementCommand.js" />
    <None Remove="LoadItems\DeductItems\WoCostItemEnumEditor.js" />
    <None Remove="Outsourcing\Commands\ForceCompleteCommand.js" />
    <None Remove="Outsourcing\Commands\InStockAddCommand.js" />
    <None Remove="Outsourcing\Commands\InStockDeleteCommand.js" />
    <None Remove="Outsourcing\Commands\InstockEditCommand.js" />
    <None Remove="Outsourcing\Commands\InStockRecordAddCommand.js" />
    <None Remove="Outsourcing\Commands\InStockSaveCommand.js" />
    <None Remove="Outsourcing\Commands\InStockSubmitCommand.js" />
    <None Remove="Outsourcing\Commands\DeleteRequestCommand.js" />
    <None Remove="Outsourcing\Commands\OutboundAddCommand.js" />
    <None Remove="Outsourcing\Commands\OutboundConfirmDetailSaveCommand.js" />
    <None Remove="Outsourcing\Commands\OutboundConfirmSnDetailAddCommand.js" />
    <None Remove="Outsourcing\Commands\OutboundConfirmSnDetailDeleteCommand.js" />
    <None Remove="Outsourcing\Commands\OutboundDeleteCommand.js" />
    <None Remove="Outsourcing\Commands\OutboundRecordAddCommand.js" />
    <None Remove="Outsourcing\Commands\OutboundRecordEditCommand.js" />
    <None Remove="Outsourcing\Commands\OutboundRecordSaveCommand.js" />
    <None Remove="Outsourcing\Commands\OutboundSubmitCommand.js" />
    <None Remove="Outsourcing\Commands\AddOutsourcingRequestCommand.js" />
    <None Remove="Outsourcing\Commands\EditOutsourcingCommand.js" />
    <None Remove="Outsourcing\Commands\SaveOutsourcingCommand.js" />
    <None Remove="Outsourcing\Commands\TemporaryAddCommand.js" />
    <None Remove="Outsourcing\Editor\OutsourcingRequestCriteriaComboPopup.js" />
    <None Remove="Outsourcing\Editor\OutsourcingRequestIdLinkComboPopup.js" />
    <None Remove="PackingPrints\Commands\PackingBarcodePrintCommand.js" />
    <None Remove="PackingPrints\Commands\PrintCommand.js" />
    <None Remove="PackingPrints\Commands\ReprintCommand.js" />
    <None Remove="PackingQC\Commands\ComfrimCommand.js" />
    <None Remove="PackingQC\Commands\PackingQcExecuteCommand.js" />
    <None Remove="PackingQC\Commands\ReportUloadCommand.js" />
    <None Remove="PackRule\Commands\QRCodeRuleSaveCommands.js" />
    <None Remove="PrepareProducts\Behaviors\PrepareRecordBehavior.js" />
    <None Remove="PrepareProducts\Commands\ComfrimCommand.js" />
    <None Remove="PrepareProducts\Commands\PrepareProductDetailAddCommand.js" />
    <None Remove="PrepareProducts\Commands\PrepareProductEditCommand.js" />
    <None Remove="PrepareProducts\Commands\PrepareProductExportCommand.js" />
    <None Remove="PrepareProducts\Commands\PrepareProductImportCommand.js" />
    <None Remove="PrepareProducts\Commands\PrepareProductSaveCommand.js" />
    <None Remove="PrepareProducts\Commands\PrepareProjectAddCommand.js" />
    <None Remove="PrepareProducts\Commands\PrepareProjectImportCommand.js" />
    <None Remove="PrepareProducts\Commands\PrepareProjectSaveCommand.js" />
    <None Remove="PrepareProducts\Commands\PrepareRecordExecuteCommand.js" />
    <None Remove="PrepareProducts\Commands\PrepareRecordExportCommand.js" />
    <None Remove="PrepareProducts\Scripts\CommonFuns.js" />
    <None Remove="ProcessProperty\Commands\ProcessPtyDLTemplateCommand.js" />
    <None Remove="ProcessProperty\Commands\ProcessPtyImportCommand.js" />
    <None Remove="ProcessProperty\Commands\ProcessPtySaveCommands.js" />
    <None Remove="ProjectDesigns\Behaviors\ProjectDesignDetailBehavior.js" />
    <None Remove="ProjectDesigns\ChildCommands\BasicPropertyAddCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\BasicPropertySaveCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\BomCommands\TreeBomAddCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\BomCommands\TreeBomDeleteCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\BomCommands\TreeBomDetailDeleteCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\BomCommands\TreeBomDetailEditCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\BomCommands\TreeBomDetailImportCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\BomCommands\TreeBomEditCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\BomCommands\TreeBomInitCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\BomCommands\TreeBomSaveCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\BomCommands\TreeBomUpdateCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\DocumentCommands\DocumentAddCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\DocumentCommands\DocumentSaveCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\DocumentCommands\DocumentUploadCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\ProductTreeAddCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\ProductTreeDeleteCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\ProductTreeInitBomCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\ProductTreeSaveCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingAddCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingBomAddCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingBomDeleteCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingBomEditCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingBomImpCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingBomInitCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingDeleteCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingDetailAddCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingDetailDeleteCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingDetailEditCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingEditCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingInitCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingPraAddCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingPraDeleteCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingPraEditCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingSaveCommand.js" />
    <None Remove="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingUpDateCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignAddCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignAgainstExamineCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignCompleteCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignDeleteCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignDetailCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignDisableCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignEditCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignEnableCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignExamineCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignSaveCommand.js" />
    <None Remove="ProjectDesigns\Commands\ProjectDesignViewCommand.js" />
    <None Remove="ProjectDesigns\Reports\Scripts\ReportBehavior.js" />
    <None Remove="Projects\Commands\ProcessStandardDeleteCommand.js" />
    <None Remove="Projects\Commands\ProcessStandardDtlAddCommand.js" />
    <None Remove="Projects\Commands\ProcessStandardDtlDeleteCommand.js" />
    <None Remove="Projects\Commands\ProcessStandardDtlEditCommand.js" />
    <None Remove="Projects\Commands\ProcessStandardEditCommand.js" />
    <None Remove="Projects\Commands\ProcessStandardExamineCommand.js" />
    <None Remove="Projects\Commands\ProcessStandardRevokeExamineCommand.js" />
    <None Remove="Projects\Commands\ProcessStandardSaveCommand.js" />
    <None Remove="Projects\Commands\ProcessStandExportCommand.js" />
    <None Remove="Projects\Commands\ProjectParamSaveCommand.js" />
    <None Remove="QTimes\Commands\QTimeStandardEditCommand.js" />
    <None Remove="QTimes\Commands\QTimeStandardSaveCommand.js" />
    <None Remove="QTimes\Commands\QTPushObjectEditCommand.js" />
    <None Remove="QTimes\Scripts\Common.js" />
    <None Remove="QTimes\Scripts\QTEndStateComboList.js" />
    <None Remove="QTimes\Scripts\QTimeStandardMessageEditor.js" />
    <None Remove="QTimes\Scripts\QTPushEditor.js" />
    <None Remove="QTimes\Scripts\QTStartStateComboList.js" />
    <None Remove="QTimes\Templates\QTRazorTemplate.txt" />
    <None Remove="Routings\ProductRoutings\Commands\AddBomCommand.js" />
    <None Remove="Routings\ProductRoutings\Commands\DeleteBomCommand.js" />
    <None Remove="Routings\ProductRoutings\Commands\EditBomCommand.js" />
    <None Remove="Routings\ProductRoutings\Controls\ProductRoutingDesignControl.js" />
    <None Remove="Routings\ProductRoutings\Scripts\ProductRoutingLayout.js" />
    <None Remove="Routings\RoutingBoms\Commands\DownloadImportFileCommand.js" />
    <None Remove="Routings\RoutingBoms\Commands\ImportRoutingBom.js" />
    <None Remove="Routings\RoutingBoms\Commands\ImportRoutingBomDetail.js" />
    <None Remove="Routings\RoutingBoms\Commands\RoutingBomAddCommand.js" />
    <None Remove="Routings\RoutingBoms\Commands\RoutingBomDetailAddCommand.js" />
    <None Remove="Routings\RoutingBoms\Commands\RoutingBomDetailEditCommand.js" />
    <None Remove="Routings\RoutingBoms\Commands\RoutingBomEditCommand.js" />
    <None Remove="Routings\RoutingBoms\Commands\RoutingBomSaveCommand.js" />
    <None Remove="Routings\RoutingBoms\Commands\ShowRoutingBomDetailCommand.js" />
    <None Remove="Routings\RoutingBoms\Scripts\Behaviors\RoutingBomDetailBehavior.js" />
    <None Remove="Routings\RoutingBoms\Scripts\RoutingProcessLookUp.js" />
    <None Remove="Routings\RoutingBoms\Scripts\RoutingProcessPropertyExtension.js" />
    <None Remove="Routings\RoutingSettings\Commands\ProductRoutingSaveCommand.js" />
    <None Remove="Routings\RoutingSettings\Scripts\RoutingSettingsLayout.js" />
    <None Remove="Routings\Scripts\RoutingBomCommonFun.js" />
    <None Remove="Validitys\Commands\ValidityAddCommand.js" />
    <None Remove="Validitys\Commands\ValiditySaveCommand.js" />
    <None Remove="Validitys\Commands\ValidityStandardImportCommand.js" />
    <None Remove="WIP\Products\Commands\ExportReportCommand.js" />
    <None Remove="WorkOrderArchives\Behaviors\ItemShortBehavior.js" />
    <None Remove="WorkOrders\Commands\AddWoBomPropertyValueCommand.js" />
    <None Remove="WorkOrders\Commands\AddWoPropertyValueCommand.js" />
    <None Remove="WorkOrders\Commands\AddWorkOrderCommand.js" />
    <None Remove="WorkOrders\Commands\BarcodeDownLoadCommand.js" />
    <None Remove="WorkOrders\Commands\CopyWorkOrderCommand.js" />
    <None Remove="WorkOrders\Commands\EditWorkOrderCommand.js" />
    <None Remove="WorkOrders\Commands\GeneraDispatchTaskCommand.js" />
    <None Remove="WorkOrders\Commands\GenerateTaskBIllCommand.js" />
    <None Remove="WorkOrders\Commands\LayoutInfoSaveCommand.js" />
    <None Remove="WorkOrders\Commands\OneKeyToPrepareCommand.js" />
    <None Remove="WorkOrders\Commands\ProcessBomAddCommand.js" />
    <None Remove="WorkOrders\Commands\ProcessBomAttentAddCommand.js" />
    <None Remove="WorkOrders\Commands\ProcessBomAttentMoveBottom.js" />
    <None Remove="WorkOrders\Commands\ProcessBomAttentMoveDown.js" />
    <None Remove="WorkOrders\Commands\ProcessBomAttentMoveTop.js" />
    <None Remove="WorkOrders\Commands\ProcessBomAttentMoveUp.js" />
    <None Remove="WorkOrders\Commands\PropertyValueDelCommand.js" />
    <None Remove="WorkOrders\Commands\ReadonlyWorkOrderCommand.js" />
    <None Remove="WorkOrders\Commands\SaveAndAddWorkOrderCommand.js" />
    <None Remove="WorkOrders\Commands\SaveAndClosedWorkOrderCommand.js" />
    <None Remove="WorkOrders\Commands\SaveWorkOrderCommand.js" />
    <None Remove="WorkOrders\Commands\SelectPackageRuleCommand.js" />
    <None Remove="WorkOrders\Commands\UpdateRoutingCommand.js" />
    <None Remove="WorkOrders\Commands\WoProcessPackUnitLookupCommand.js" />
    <None Remove="WorkOrders\Commands\WorkBomAddCommand.js" />
    <None Remove="WorkOrders\Commands\WorkBomEditCommand.js" />
    <None Remove="WorkOrders\Commands\WorkOrderAdvanceCommand.js" />
    <None Remove="WorkOrders\Commands\WorkOrderBomPropertyEditCommand.js" />
    <None Remove="WorkOrders\Commands\WorkOrderCloseCommand.js" />
    <None Remove="WorkOrders\Commands\WorkOrderCompletionCommand.js" />
    <None Remove="WorkOrders\Commands\WorkOrderImportCommand.js" />
    <None Remove="WorkOrders\Commands\WorkOrderPauseCommand.js" />
    <None Remove="WorkOrders\Commands\WorkOrderProcessBomPropertyEditCommand.js" />
    <None Remove="WorkOrders\Commands\WorkOrderResumeCommand.js" />
    <None Remove="WorkOrders\Common\WoCommonFun.js" />
    <None Remove="WorkOrders\Editors\ProcessBomRoutingProcess.js" />
    <None Remove="WorkOrders\Editors\ReworkSnEditor.js" />
    <None Remove="WorkOrders\Editors\TemplateBarcodeRule.js" />
    <None Remove="WorkOrders\Editors\WorkOrderProvalueDefinitionCombolist.js" />
    <None Remove="WorkOrders\Editors\WorkOrderRoutingDisplayEditor.js" />
    <None Remove="WorkOrders\Editors\WorkOrderRoutingVersion.js" />
    <None Remove="WorkOrders\Reworks\Commands\RemoveBarcodeCommand.js" />
    <None Remove="WorkOrders\Reworks\Commands\UnionBarcodeCommand.js" />
    <None Remove="WorkOrders\Reworks\Commands\UnionBarcodeSaveCommand.js" />
    <None Remove="WorkOrders\Reworks\Commands\UnionBarcodeSelCommand.js" />
    <None Remove="WorkOrders\Reworks\Scripts\UnionBarcodeBehavior.js" />
    <None Remove="WorkOrders\Reworks\Scripts\WorkOrderUnionBarcodeBehavior.js" />
    <None Remove="WorkOrders\Scripts\BaseWorkOrderDetailBehavior.js" />
    <None Remove="WorkOrders\Scripts\CreateWorkOrderBehavior.js" />
    <None Remove="WorkOrders\Scripts\EditReadWorkOrderBehavior.js" />
    <None Remove="WorkOrders\Scripts\UpdateRoutingControl.js" />
    <None Remove="WorkOrders\Scripts\WorkOrderBehavior.js" />
    <None Remove="WorkOrders\ViewModels\PropertyValueEditor.js" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\..\..\..\.sonarlint\sie.smom\CSharp\SonarLint.xml" Link="SonarLint.xml" />
  </ItemGroup>
  <ItemGroup>
    <ApplicationDefinition Include="LineAndon\Commands\AndonLineLabelPrintCommand.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Andon\Commands\ThresholdDLTemplateCommand.js" />
    <EmbeddedResource Include="Andon\Commands\ThresholdImportCommand.js" />
    <EmbeddedResource Include="BlueLable\Commands\BlueLableLevelDLTemplateCommand.js" />
    <EmbeddedResource Include="BlueLable\Commands\BlueLableLevelImportCommand.js" />
    <EmbeddedResource Include="Capacitys\Commands\StandardCapacityDLTemplateCommand.js" />
    <EmbeddedResource Include="Capacitys\Commands\StandardCapacityImportCommand.js" />
    <EmbeddedResource Include="Checker\Commands\CheckerUpholdDLTemplateCommand.js" />
    <EmbeddedResource Include="Checker\Commands\CheckerUpholdImportCommand.js" />
    <EmbeddedResource Include="DataBarcode\Commands\DataBarcodeDeleteCommand.js" />
    <EmbeddedResource Include="DataBarcode\Commands\DataBarcodeImportCommand.js" />
    <EmbeddedResource Include="DataBarcode\Commands\DataBarcodeLabelPrintCommand.js" />
    <EmbeddedResource Include="Fixture\Commands\FixtureUpholdDLTemplateCommand.js" />
    <EmbeddedResource Include="Fixture\Commands\FixtureUpholdImportCommand.js" />
    <EmbeddedResource Include="ItemChecker\Commands\CheckerItemDLTemplateCommand.js" />
    <EmbeddedResource Include="ItemChecker\Commands\CheckerItemImportCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemDLTemplateCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemImportCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemImportItemCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemImportProcessCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemImportUniqueCodeCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemLabelPrintCommand.js" />
    <EmbeddedResource Include="ItemFixture\Commands\FixtureItemDLTemplateCommand.js" />
    <EmbeddedResource Include="ItemFixture\Commands\FixtureItemImportCommand.js" />
    <EmbeddedResource Include="ItemLine\Commands\ProductLineDLTemplateCommand.js" />
    <EmbeddedResource Include="ItemLine\Commands\ProductLineImportCommand.js" />
    <EmbeddedResource Include="ItemLine\Commands\ProductLineImportItemCommand.js" />
    <EmbeddedResource Include="ItemLine\Commands\ProductLineImportProcessCommand.js" />
    <EmbeddedResource Include="ItemLine\Commands\ProductLineImportWipResourceCommand.js" />
    <EmbeddedResource Include="ItemProcess\Commands\ProcessItemDLTemplateCommand.js" />
    <EmbeddedResource Include="ItemProcess\Commands\ProcessItemImportCommand.js" />
    <EmbeddedResource Include="LineAndon\Commands\AdonlineLabelPrintCommand.js" />
    <EmbeddedResource Include="LineAndon\Commands\AndonLineDLTemplateCommand.js" />
    <EmbeddedResource Include="LineAndon\Commands\AndonLineImportCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\OutboundConfirmDetailSaveCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\OutboundConfirmSnDetailAddCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\OutboundConfirmSnDetailDeleteCommand.js" />
    <EmbeddedResource Include="PackingQC\Commands\ComfrimCommand.js" />
    <EmbeddedResource Include="PackingQC\Commands\PackingQcExecuteCommand.js" />
    <EmbeddedResource Include="PackingQC\Commands\ReportUloadCommand.js" />
    <EmbeddedResource Include="PackRule\Commands\QRCodeRuleSaveCommands.js" />
    <EmbeddedResource Include="ProcessProperty\Commands\ProcessPtyDLTemplateCommand.js" />
    <EmbeddedResource Include="ProcessProperty\Commands\ProcessPtyImportCommand.js" />
    <EmbeddedResource Include="ProcessProperty\Commands\ProcessPtySaveCommands.js" />
    <EmbeddedResource Include="ProjectDesigns\Behaviors\ProjectDesignDetailBehavior.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BomCommands\TreeBomDetailImportCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\DocumentCommands\DocumentAddCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\DocumentCommands\DocumentSaveCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\DocumentCommands\DocumentUploadCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingBomAddCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingBomDeleteCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingBomEditCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingBomImpCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingBomInitCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingDeleteCommand.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BasicPropertyAddCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BasicPropertySaveCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BomCommands\TreeBomAddCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BomCommands\TreeBomDeleteCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BomCommands\TreeBomDetailDeleteCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BomCommands\TreeBomDetailEditCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BomCommands\TreeBomEditCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BomCommands\TreeBomInitCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BomCommands\TreeBomSaveCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\BomCommands\TreeBomUpdateCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\ProductTreeAddCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\ProductTreeDeleteCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\ProductTreeInitBomCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\ProductTreeSaveCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingAddCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingDetailAddCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingDetailDeleteCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingDetailEditCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingEditCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingInitCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingPraAddCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingPraDeleteCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingPraEditCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingSaveCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\ChildCommands\RoutingCommands\TreeRoutingUpDateCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignAddCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignAgainstExamineCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignCompleteCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignDeleteCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignDetailCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignDisableCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignEditCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignEnableCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignExamineCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignSaveCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Commands\ProjectDesignViewCommand.js" />
    <EmbeddedResource Include="ProjectDesigns\Reports\Scripts\ReportBehavior.js" />
    <EmbeddedResource Include="Projects\Commands\ProcessStandardDeleteCommand.js" />
    <EmbeddedResource Include="Projects\Commands\ProcessStandardEditCommand.js" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="QTimes\Templates\QTRazorTemplate.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemImportEquipCommand.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Andon\Commands\AndonUpholdSaveCommands.js" />
    <EmbeddedResource Include="BarcodeProcesses\Commands\AfterAddProcessDetailCommand.js" />
    <EmbeddedResource Include="BarcodeProcesses\Commands\SynWoProcessListCommand.js" />
    <EmbeddedResource Include="BarcodeProcesses\Commands\WoProcessDetailSaveCommand.js" />
    <EmbeddedResource Include="BarcodeProcesses\Scripts\EmployeeMultiComboPopup.js" />
    <EmbeddedResource Include="BatchGeneration\Commands\BatchWoGenerateCommand.js" />
    <EmbeddedResource Include="BatchGeneration\Commands\GenerateAndPrintCommand.js" />
    <EmbeddedResource Include="BatchGeneration\Commands\GenerateCommand.js" />
    <EmbeddedResource Include="BatchProductRoutings\Commands\BatchProductCriteriaCommand.js" />
    <EmbeddedResource Include="BatchProductRoutings\Commands\PauseCommand.js" />
    <EmbeddedResource Include="BatchProductRoutings\Controls\BatchRoutingDesignControl.js" />
    <EmbeddedResource Include="BatchProductRoutings\Scripts\BatchRoutingLayout.js" />
    <EmbeddedResource Include="BatchWIP\Commands\ExportReportCommand.js" />
    <EmbeddedResource Include="BatchWIP\Scripts\BatchWipProductProcessBehavior.js" />
    <EmbeddedResource Include="BatchWIP\Scripts\BatchWipProductProcessDtlBehavior.js" />
    <EmbeddedResource Include="BatchWIP\Scripts\BatchWipRecordBehavior.js" />
    <EmbeddedResource Include="Checker\Commands\CheckerUpholdSaveCommands.js" />
    <EmbeddedResource Include="Common\Commands\ImportDataCommonCommand.js" />
    <EmbeddedResource Include="Common\CommonFuns.js" />
    <EmbeddedResource Include="Edge\Commands\ReSubmitMessageCommand.js" />
    <EmbeddedResource Include="Fixture\Commands\FixtureUpholdSaveCommands.js" />
    <EmbeddedResource Include="InspectionStandards\Commands\ImportInspectionCommand.js" />
    <EmbeddedResource Include="InspectionStandards\Commands\InspectionAddCommand.js" />
    <EmbeddedResource Include="InspectionStandards\Commands\InspectionSaveCommand.js" />
    <EmbeddedResource Include="ItemChecker\Commands\CheckerItemDeleteCommand.js" />
    <EmbeddedResource Include="ItemChecker\Commands\CheckerItemDisableCommand.js" />
    <EmbeddedResource Include="ItemChecker\Commands\CheckerItemEditCommand.js" />
    <EmbeddedResource Include="ItemChecker\Commands\CheckerItemEnableCommand.js" />
    <EmbeddedResource Include="ItemChecker\Commands\CheckerItemSaveCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemDeleteCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemDisableCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemEditCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemEnableCommand.js" />
    <EmbeddedResource Include="ItemEquipAccount\Commands\EquipAccountItemSaveCommand.js" />
    <EmbeddedResource Include="ItemFixture\Commands\FixtureItemDeleteCommand.js" />
    <EmbeddedResource Include="ItemFixture\Commands\FixtureItemDisableCommand.js" />
    <EmbeddedResource Include="ItemFixture\Commands\FixtureItemEditCommand.js" />
    <EmbeddedResource Include="ItemFixture\Commands\FixtureItemEnableCommand.js" />
    <EmbeddedResource Include="ItemFixture\Commands\FixtureItemSaveCommand.js" />
    <EmbeddedResource Include="ItemLine\Commands\ProductLineDeleteCommand.js" />
    <EmbeddedResource Include="ItemLine\Commands\ProductLineDisableCommand.js" />
    <EmbeddedResource Include="ItemLine\Commands\ProductLineEditCommands.js" />
    <EmbeddedResource Include="ItemLine\Commands\ProductLineEnableCommand.js" />
    <EmbeddedResource Include="ItemLine\Commands\ProductLineSaveCommands.js" />
    <EmbeddedResource Include="ItemProcess\Commands\ProcessItemDeleteCommand.js" />
    <EmbeddedResource Include="ItemProcess\Commands\ProcessItemDisableCommand.js" />
    <EmbeddedResource Include="ItemProcess\Commands\ProcessItemEditCommand.js" />
    <EmbeddedResource Include="ItemProcess\Commands\ProcessItemEnableCommand.js" />
    <EmbeddedResource Include="ItemProcess\Commands\ProcessItemSaveCommand.js" />
    <EmbeddedResource Include="LoadItems\DeductItems\Commands\WoCostItemAddCommand.js" />
    <EmbeddedResource Include="LoadItems\DeductItems\Commands\WoCostItemCloseCommand.js" />
    <EmbeddedResource Include="LoadItems\DeductItems\Commands\WoCostItemDeleteCommand.js" />
    <EmbeddedResource Include="LoadItems\DeductItems\Commands\WoCostItemEditCommand.js" />
    <EmbeddedResource Include="LoadItems\DeductItems\Commands\WoCostItemSaveCommand.js" />
    <EmbeddedResource Include="LoadItems\DeductItems\Commands\WoCostItemSubmitCommand.js" />
    <EmbeddedResource Include="LoadItems\DeductItems\Commands\WoCostItemSupplementCommand.js" />
    <EmbeddedResource Include="LoadItems\DeductItems\Scripts\WoCostItemEnumEditor.js" />
    <EmbeddedResource Include="Outsourcing\Commands\InStockRecordAddCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\OutboundRecordEditCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\OutboundRecordSaveCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\InStockSaveCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\InStockAddCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\DeleteRequestCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\InStockDeleteCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\OutboundDeleteCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\InstockEditCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\OutboundAddCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\InStockSubmitCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\ForceCompleteCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\OutboundSubmitCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\EditOutsourcingCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\SaveOutsourcingCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\TemporaryAddCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\AddOutsourcingRequestCommand.js" />
    <EmbeddedResource Include="Outsourcing\Commands\OutboundRecordAddCommand.js" />
    <EmbeddedResource Include="Outsourcing\Editor\OutsourcingRequestIdLinkComboPopup.js" />
    <EmbeddedResource Include="Outsourcing\Editor\OutsourcingRequestCriteriaComboPopup.js" />
    <EmbeddedResource Include="PackingPrints\Commands\PackingBarcodePrintCommand.js" />
    <EmbeddedResource Include="PackingPrints\Commands\PrintCommand.js" />
    <EmbeddedResource Include="PackingPrints\Commands\ReprintCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Behaviors\PrepareRecordBehavior.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\ComfrimCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\PrepareProductDetailAddCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\PrepareProductEditCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\PrepareProductExportCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\PrepareProductImportCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\PrepareProductSaveCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\PrepareProjectAddCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\PrepareProjectImportCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\PrepareProjectSaveCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\PrepareRecordExecuteCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Commands\PrepareRecordExportCommand.js" />
    <EmbeddedResource Include="PrepareProducts\Scripts\CommonFuns.js" />
    <EmbeddedResource Include="Projects\Commands\ProcessStandardDtlAddCommand.js" />
    <EmbeddedResource Include="Projects\Commands\ProcessStandardDtlDeleteCommand.js" />
    <EmbeddedResource Include="Projects\Commands\ProcessStandardDtlEditCommand.js" />
    <EmbeddedResource Include="Projects\Commands\ProcessStandardExamineCommand.js" />
    <EmbeddedResource Include="Projects\Commands\ProcessStandardRevokeExamineCommand.js" />
    <EmbeddedResource Include="Projects\Commands\ProcessStandardSaveCommand.js" />
    <EmbeddedResource Include="Projects\Commands\ProcessStandExportCommand.js">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Projects\Commands\ProjectParamSaveCommand.js" />
    <EmbeddedResource Include="QTimes\Commands\QTimeStandardEditCommand.js" />
    <EmbeddedResource Include="QTimes\Commands\QTimeStandardSaveCommand.js" />
    <EmbeddedResource Include="QTimes\Commands\QTPushObjectEditCommand.js" />
    <EmbeddedResource Include="QTimes\Scripts\Common.js" />
    <EmbeddedResource Include="QTimes\Scripts\QTEndStateComboList.js" />
    <EmbeddedResource Include="QTimes\Scripts\QTimeStandardMessageEditor.js" />
    <EmbeddedResource Include="QTimes\Scripts\QTPushEditor.js" />
    <EmbeddedResource Include="QTimes\Scripts\QTStartStateComboList.js" />
    <EmbeddedResource Include="Routings\ProductRoutings\Commands\AddBomCommand.js" />
    <EmbeddedResource Include="Routings\ProductRoutings\Commands\DeleteBomCommand.js" />
    <EmbeddedResource Include="Routings\ProductRoutings\Commands\EditBomCommand.js" />
    <EmbeddedResource Include="Routings\ProductRoutings\Controls\ProductRoutingDesignControl.js" />
    <EmbeddedResource Include="Routings\ProductRoutings\Scripts\ProductRoutingLayout.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Commands\DownloadImportFileCommand.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Commands\ImportRoutingBom.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Commands\ImportRoutingBomDetail.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Commands\RoutingBomAddCommand.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Commands\RoutingBomDetailAddCommand.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Commands\RoutingBomDetailEditCommand.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Commands\RoutingBomEditCommand.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Commands\RoutingBomSaveCommand.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Commands\ShowRoutingBomDetailCommand.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Scripts\Behaviors\RoutingBomDetailBehavior.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Scripts\RoutingProcessLookUp.js" />
    <EmbeddedResource Include="Routings\RoutingBoms\Scripts\RoutingProcessPropertyExtension.js" />
    <EmbeddedResource Include="Routings\RoutingSettings\Commands\ProductRoutingSaveCommand.js" />
    <EmbeddedResource Include="Routings\RoutingSettings\Scripts\RoutingSettingsLayout.js" />
    <EmbeddedResource Include="Routings\Scripts\RoutingBomCommonFun.js" />
    <EmbeddedResource Include="Validitys\Commands\ValidityStandardImportCommand.js" />
    <EmbeddedResource Include="Validitys\Commands\ValidityAddCommand.js" />
    <EmbeddedResource Include="Validitys\Commands\ValiditySaveCommand.js" />
    <EmbeddedResource Include="WIP\Pressure\Commands\WipPressurePrintTPLDLTemplateCommand.js" />
    <EmbeddedResource Include="WIP\Pressure\Commands\WipPressurePrintTPLImportCommand.js" />
    <EmbeddedResource Include="WIP\Products\Commands\ExportReportCommand.js" />
    <EmbeddedResource Include="WorkOrderArchives\Behaviors\ItemShortBehavior.js" />
    <EmbeddedResource Include="WorkOrders\Commands\AddWoBomPropertyValueCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\AddWoPropertyValueCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\AddWorkOrderCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\BarcodeDownLoadCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\CopyWorkOrderCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\EditWorkOrderCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\GeneraDispatchTaskCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\LayoutInfoSaveCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\OneKeyToPrepareCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\ProcessBomAddCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\ProcessBomAttentAddCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\ProcessBomAttentMoveBottom.js" />
    <EmbeddedResource Include="WorkOrders\Commands\ProcessBomAttentMoveDown.js" />    
    <EmbeddedResource Include="WorkOrders\Commands\ProcessBomAttentMoveTop.js" />
    <EmbeddedResource Include="WorkOrders\Commands\ProcessBomAttentMoveUp.js" />
    <EmbeddedResource Include="WorkOrders\Commands\PropertyValueDelCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\ReadonlyWorkOrderCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\SaveAndAddWorkOrderCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\SaveAndClosedWorkOrderCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\SaveWorkOrderCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\SelectPackageRuleCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\UpdateRoutingCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\WoProcessPackUnitLookupCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\WorkBomAddCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\WorkBomEditCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\WorkOrderBomPropertyEditCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\WorkOrderCloseCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\WorkOrderCompletionCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\WorkOrderImportCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\WorkOrderPauseCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\WorkOrderProcessBomPropertyEditCommand.js" />
    <EmbeddedResource Include="WorkOrders\Commands\WorkOrderResumeCommand.js" />
    <EmbeddedResource Include="WorkOrders\Common\WoCommonFun.js" />
    <EmbeddedResource Include="WorkOrders\Editors\ProcessBomRoutingProcess.js" />
    <EmbeddedResource Include="WorkOrders\Editors\ReworkSnEditor.js" />
    <EmbeddedResource Include="WorkOrders\Editors\TemplateBarcodeRule.js" />
    <EmbeddedResource Include="WorkOrders\Editors\WorkOrderProvalueDefinitionCombolist.js" />
    <EmbeddedResource Include="WorkOrders\Editors\WorkOrderRoutingVersion.js" />
    <EmbeddedResource Include="WorkOrders\Reworks\Commands\RemoveBarcodeCommand.js" />
    <EmbeddedResource Include="WorkOrders\Reworks\Commands\UnionBarcodeCommand.js" />
    <EmbeddedResource Include="WorkOrders\Reworks\Commands\UnionBarcodeSaveCommand.js" />
    <EmbeddedResource Include="WorkOrders\Reworks\Commands\UnionBarcodeSelCommand.js" />
    <EmbeddedResource Include="WorkOrders\Reworks\Scripts\WorkOrderUnionBarcodeBehavior.js" />
    <EmbeddedResource Include="WorkOrders\Scripts\BaseWorkOrderDetailBehavior.js" />
    <EmbeddedResource Include="WorkOrders\Scripts\CreateWorkOrderBehavior.js" />    
    <EmbeddedResource Include="WorkOrders\Scripts\EditReadWorkOrderBehavior.js" />
    <EmbeddedResource Include="WorkOrders\Scripts\UpdateRoutingControl.js" />
    <EmbeddedResource Include="WorkOrders\Scripts\WorkOrderBehavior.js" />
    <EmbeddedResource Include="WorkReportPlans\Commands\InitializationCommand.js" />
    <EmbeddedResource Include="WorkReportPlans\Commands\SetDefaultCommand.js" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Items\SIE.Web.Items\SIE.Web.Items.csproj" />
    <ProjectReference Include="..\..\..\Common\Resources\SIE.Web.Resources\SIE.Web.Resources.csproj" />
    <ProjectReference Include="..\..\..\Common\Techs\SIE.Web.Tech\SIE.Web.Tech.csproj" />
    <ProjectReference Include="..\..\Barcodes\SIE.Web.Barcodes\SIE.Web.Barcodes.csproj" />
    <ProjectReference Include="..\SIE.MES\SIE.MES.csproj" /> 
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="WorkOrders\Commands\WorkOrderAdvanceCommand.js" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="LineAndon\Commands\新文件夹\" />
  </ItemGroup>
</Project>
